// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkEjSSDaaTjcQHeHT0FuDYYxC_U_7GhC4',
    appId: '1:840260685817:web:9edfc8c4e9b0a1b2e9f728',
    messagingSenderId: '840260685817',
    projectId: 'authtutorial-4a8f9',
    authDomain: 'authtutorial-4a8f9.firebaseapp.com',
    storageBucket: 'authtutorial-4a8f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKAJcVMXWFuLYQ529bNY9RvyKD08IQn38',
    appId: '1:840260685817:android:9e028f7878220b83e9f728',
    messagingSenderId: '840260685817',
    projectId: 'authtutorial-4a8f9',
    storageBucket: 'authtutorial-4a8f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZitNMBEja8AEK_Y9L0CCG_I4pRn5CF5k',
    appId: '1:840260685817:ios:f7aacf43bba65242e9f728',
    messagingSenderId: '840260685817',
    projectId: 'authtutorial-4a8f9',
    storageBucket: 'authtutorial-4a8f9.appspot.com',
    iosBundleId: 'com.example.dummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZitNMBEja8AEK_Y9L0CCG_I4pRn5CF5k',
    appId: '1:840260685817:ios:ab9de0216068d658e9f728',
    messagingSenderId: '840260685817',
    projectId: 'authtutorial-4a8f9',
    storageBucket: 'authtutorial-4a8f9.appspot.com',
    iosBundleId: 'com.example.dummy.RunnerTests',
  );
}
